# Launches and drives Camoufox over Playwright's Juggler protocol.
module Crystalfaux
  # The version of the shard.
  VERSION = "0.1.0"
end

require "./crystalfaux/errors"
require "./crystalfaux/juggler/*"
require "./crystalfaux/launcher"
require "./crystalfaux/launcher/*"
require "./crystalfaux/protocol"
require "./crystalfaux/protocol/*"
require "./crystalfaux/resource_type"
require "./crystalfaux/url_glob"
require "./crystalfaux/fingerprint"
require "./crystalfaux/fingerprint/*"
require "./crystalfaux/proxy"
require "./crystalfaux/cookie"
require "./crystalfaux/request"
require "./crystalfaux/response"
require "./crystalfaux/wait_until"
require "./crystalfaux/world"
require "./crystalfaux/frame"
require "./crystalfaux/page"
require "./crystalfaux/page/*"
require "./crystalfaux/context"
require "./crystalfaux/browser"
require "./crystalfaux/browser/*"
require "./crystalfaux/pool"
require "./crystalfaux/fetch"
require "./crystalfaux/fetch/*"
